# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheViralPages' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheViralPages
  pod 'Firebase/Messaging'
end

target 'TheViralPages-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TheViralPages-tvOS

end
