# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WordpressRN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WordpressRN
  pod 'Firebase/Messaging'

  target 'WordpressRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WordpressRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'WordpressRN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WordpressRN-tvOS

end
